const { withAndroidManifest } = require('@expo/config-plugins');

/**
 * Declare the intents the Call / WhatsApp buttons rely on.
 *
 * From Android 11 (API 30) package visibility hides every app that is not
 * matched by a <queries> entry, so `tel:` and `whatsapp:` links fail to
 * resolve unless they are declared here. The native project is committed, but
 * this keeps the declarations in place if it is ever regenerated by prebuild.
 */
const CONTACT_INTENTS = [
  { action: 'android.intent.action.DIAL', scheme: 'tel' },
  { action: 'android.intent.action.VIEW', scheme: 'tel' },
  { action: 'android.intent.action.SENDTO', scheme: 'smsto' },
  { action: 'android.intent.action.VIEW', scheme: 'whatsapp' },
];

const CONTACT_PACKAGES = ['com.whatsapp', 'com.whatsapp.w4b'];

module.exports = function withContactQueries(config) {
  return withAndroidManifest(config, (mod) => {
    const manifest = mod.modResults.manifest;
    manifest.queries = manifest.queries ?? [{}];

    const queries = manifest.queries[0];
    queries.intent = queries.intent ?? [];
    queries.package = queries.package ?? [];

    for (const { action, scheme } of CONTACT_INTENTS) {
      const exists = queries.intent.some(
        (entry) =>
          entry.action?.[0]?.$?.['android:name'] === action &&
          entry.data?.[0]?.$?.['android:scheme'] === scheme
      );
      if (exists) continue;

      queries.intent.push({
        action: [{ $: { 'android:name': action } }],
        data: [{ $: { 'android:scheme': scheme } }],
      });
    }

    for (const name of CONTACT_PACKAGES) {
      const exists = queries.package.some((entry) => entry.$?.['android:name'] === name);
      if (!exists) queries.package.push({ $: { 'android:name': name } });
    }

    return mod;
  });
};
